name: CI/CD

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: 165.99.102.74
          port: 7111
          username: olt
          password: a1234
          script: |
            cd /home/olt/olt-app
            git pull origin master
            ./setup.sh
